language: python
python:
  - '2.7'
script: ./unittests
deploy:
  provider: lambda
  function_name: myBirthdayInPi
  region: us-east-1
  role: arn:aws:iam::984814083532:role/lambda_basic_execution
  runtime: python3.6
  module_name: birthday_in_pi
  handler_name: lambda_handler
  zip: ./src
  access_key_id: AKIAJQUQMKWAGKTVWFFA
  on:
    branch: master
  secret_access_key: AKIAJQUQMKWAGKTVWFFA
